### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by machulong** [TomasTrnkaPLC/Lotto-Number-Prediction#1]
Thanks for your sharing!Whether we can use more than seven numbers to predict the first prize,or predict the chance of every number for next draw?

**Comment by TomasTrnkaPLC** [comment]
Hi.
You can use one number, but also 100. The system is flexible and the layers are based on the number of data.
Note:
 Check a data_compare_array_set to adjust the number for verification (If you train and validate model) or let it if you just predict. The next parameter is bream_with , which is a variable to "How many predictions do you want to see, from best to wrost"
